<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\mlnet-anomaly-detection-transactions\mlnet-anomaly-detection-transactions.csproj" />
  </ItemGroup>

  <ItemGroup>
   <None Update="compras_cartao.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
   </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="5.0.0" />
    <PackageReference Include="Microsoft.ML.AutoML" Version="0.23.0" />
    <PackageReference Include="Microsoft.ML.LightGbm" Version="5.0.0" />
  </ItemGroup>

   
</Project>
